# Generated by Django 2.1.4 on 2019-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings_waiting_list',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('tyype', models.CharField(max_length=50)),
            ],
        ),
    ]
