# Generated by Django 2.1.4 on 2019-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_listings_waiting_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_viewings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
