# Generated by Django 2.1.4 on 2019-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_booked_viewings'),
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('rent_buy', models.CharField(max_length=10)),
                ('property_picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
