# Generated by Django 2.1.4 on 2019-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
