# Generated by Django 2.1.4 on 2019-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_auto_20190110_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
