# Generated by Django 2.1.4 on 2019-01-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0006_auto_20190114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_viewings',
            name='property_id',
            field=models.IntegerField(blank=True),
        ),
    ]
