# Generated by Django 2.1.4 on 2019-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0007_auto_20190116_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='area',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='bathroom_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='bedroom_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='dining_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='entrance_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='garage',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='kitchen_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='patio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='sitting_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
